apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/cbd3354-435500/backend
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "34.44.131.30"
        - name: DB_NAME
          value: "db1"
        - name: DB_USER
          value: "dbuser1"
        - name: DB_PASS
          value: "dbuser1"
